### ISSUE TITLE
Failed hash calculation while log errors when using default Logger in NestJS v9.3.0 and later

### ISSUE THREAD

**Issue by KillWolfVlad** [Byndyusoft/node-pino-logger-factory#148]
See https://github.com/nestjs/nest/pull/10531 for more details

**Comment by KillWolfVlad** [comment]
Может быть не использовать default Logger?

https://github.com/Byndyusoft/nest-kafka/blob/master/src/consumer/exceptions/kafkaConsumerErrorTopicExceptionFilter.ts#L43-L45

Замечание от @step1989

**Comment by litichevskiydv** [comment]
К следующему стендапу @KillWolfVlad либо делегирует либо заканчивает задачу
